version: '3.1'

#volumes:
#  pg_cafe:

services:
  cafe_db:
      image: postgres
      restart: always
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cafe_db
#      volumes:
#        - pg_cafe:/var/lib/postgresql/data
      ports:
      - "5432:5432"